//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 02:46:08 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://negro.it/lm/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.negro.lm.ws;
